image: node:16.14.0
stages:
  - install
  - build
  - deploy

cache:
  key: nm
  paths:
    - nodo_modules/

job 0:
  stage: install
  script: 
    - node -v
    - npm config set registry https://registry.npm.taobao.org
    - npm install
job 1:
  stage: build
  script:
    - npm run build
    - echo 'build 完成'
job 2:
  stage: deploy
  script: echo 'deploy'
