image: node:16.14.0
stages:
  - build
  - deploy

cache:
  paths:
    - nodo_modules/

job 1:
  stage: build
  script: 
    - node -v
    - npm -v
    - npm config set registry https://registry.npm.taobao.org
    - npm i --legacy-peer-deps
    - npm run build
  artifacts:
    name: 'bundle'
    paths: 
      - dist/
      
job 2:
  stage: deploy
  script: echo 'deploy'
