image: node:16.14.0
stages:
  - install
  - build
  - deploy

job install:
  stage: install
  script: 
    - node -v
    - npm -v
    - npm config set registry https://registry.npm.taobao.org
    - npm i --legacy-peer-deps
  cache:
    untracked: true
    paths:
      - node_modules/

job build:
  stage: build
  script: 
    - export CI=false
    - npm run build
  cache:
    untracked: true
    paths:
      - node_modules/
  artifacts:
    name: 'bundle'
    paths: 
      - build/

job deploy:
  stage: deploy
  script: echo 'deploy'
